# Use built-in OpenAPI ruleset
extends: ["spectral:oas"]

# Define custom rules
rules:
  # Rule to ensure tags are defined
  tag-description:
    description: All tags must have a description.
    given: $.tags[*]
    severity: warn
    then:
      field: description
      function: truthy
      
  # Rule to enforce kebab-case on paths
  paths-kebab-case:
    description: Paths should be kebab-case.
    given: $.paths[*]~
    severity: error
    then:
      function: pattern
      functionOptions:
        match: "^/([a-z0-9-:]+)*$"
