openapi: 3.0.0                                                          
  info:       
    title: Test                                                           
    version: 1.0.0                                                        
  paths:                                                                  
    /users:                                                               
      x-internal: true                                                    
      get:                                                                
        responses:                                                        
          "200":                                                          
            description: OK   
